apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-api
  labels:
    app: sentiment-analysis-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-analysis-api
  template:
    metadata:
      labels:
        app: sentiment-analysis-api
    spec:
      containers:
      - name: sentiment-analysis-api
        image: datascientest/fake-api:1.0.0
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: my-config-map